import type { ScenarioInput } from "@netlify/axis";
import { withSkillVariants } from "../helpers/variants";

// The skill recommends persisting generated image bytes to Netlify Blobs and
// serving a URL back, rather than returning multi-MB base64 in the response.
// The prompt EXPLICITLY asks for persistence, so returning inline base64 is the
// thing to avoid — but producing base64 from the model is the model's native
// output and must NOT itself be treated as a failure.
export default {
  name: "AI Gateway: persist a generated image to Netlify Blobs",
  prompt:
    "Create a Netlify function at netlify/functions/poster.ts mounted at /api/poster that accepts POST { prompt: string }, generates an image with the AI Gateway, SAVES it to storage, and returns a URL the browser can load — I don't want multi-megabyte base64 in the JSON response.",
  judge: [
    {
      check:
        "Generates the image with `@google/genai` and a Gemini image model (image gen on the gateway is Gemini-only) — not OpenAI image models — using a bare `new GoogleGenAI({})` and no `GEMINI_API_KEY` / `GOOGLE_API_KEY` set.",
    },
    {
      check:
        "Persists the generated bytes to Netlify Blobs: gets a store via `getStore(...)` and writes with `store.set(...)`, decoding the model's base64 to a Buffer/bytes first (e.g. `Buffer.from(base64, 'base64')`).",
    },
    {
      check:
        "Returns a URL or key the client can fetch (e.g. an endpoint that streams the stored blob), NOT the raw multi-MB base64 in the response body.",
    },
    {
      check:
        "Does NOT treat the model returning base64 `inlineData` as an error — extracting base64 from the response part is the correct way to get the bytes; the scenario is about persisting them, not avoiding base64 from the model.",
    },
    {
      check:
        "Stores/serves with an appropriate content type (e.g. blob metadata `contentType: 'image/png'` or a correct `Content-Type` on the serving response).",
    },
    {
      check:
        "Uses `Netlify.env.get(...)` (not `process.env`) for any env access and the modern function signature with a config exporting path: '/api/poster'.",
    },
  ],
  variants: withSkillVariants(),
} satisfies ScenarioInput;
