#!/usr/bin/env python3
"""Generate the Kiro steering files at steering/ from skills/buildkite-*/SKILL.md.

Source of truth: skills/buildkite-*/SKILL.md (the Claude/Cursor skills).
Generated outputs (do not hand-edit):
  - steering/<short>.md     (steering file per skill)
  - steering/<short>/{references,examples}/  (symlinks)
"""

import os
import re
import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SKILLS_DIR = REPO / "skills"
STEERING_DIR = REPO / "steering"

GENERATED_HEADER = (
    "<!-- GENERATED by scripts/build-power.py from skills/{src}/SKILL.md. "
    "Do not edit by hand. -->\n\n"
)


def parse_scalar(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in ("'", '"'):
        return value[1:-1]
    return value


def parse_frontmatter(frontmatter: str, source: Path) -> dict[str, str]:
    """Parse the small YAML subset used by SKILL.md frontmatter.

    Supported forms are plain or quoted scalar values and folded blocks:
      key: value
      key: "value"
      key: >
        folded text
    """
    meta: dict[str, str] = {}
    lines = frontmatter.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        if not line.strip():
            i += 1
            continue

        if line.startswith((" ", "\t")) or ":" not in line:
            raise SystemExit(f"{source}: unsupported frontmatter line: {line!r}")

        key, value = line.split(":", 1)
        key = key.strip()
        value = value.strip()
        if not key:
            raise SystemExit(f"{source}: unsupported frontmatter line: {line!r}")

        if value == ">":
            block_lines = []
            i += 1
            while i < len(lines):
                block_line = lines[i]
                if block_line and not block_line.startswith((" ", "\t")):
                    break
                block_lines.append(block_line.strip())
                i += 1
            meta[key] = " ".join(part for part in block_lines if part)
            continue

        meta[key] = parse_scalar(value)
        i += 1

    return meta


def parse_skill(skill_md: Path):
    text = skill_md.read_text()
    m = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.DOTALL)
    if not m:
        raise SystemExit(f"{skill_md}: missing YAML frontmatter")
    meta = parse_frontmatter(m.group(1), skill_md)
    for key in ("name", "description"):
        if key not in meta:
            raise SystemExit(f"{skill_md}: missing required frontmatter key: {key}")
    body = m.group(2).lstrip("\n")
    return meta, body


def rewrite_links(body: str, short: str) -> str:
    """Rewrite `references/foo` and `examples/foo` to `<short>/references/foo`."""
    return re.sub(
        r"`(references|examples)/([^`]+)`",
        rf"`{short}/\1/\2`",
        body,
    )


def write_steering_file(short: str, src: str, meta: dict, body: str) -> None:
    STEERING_DIR.mkdir(parents=True, exist_ok=True)
    out = STEERING_DIR / f"{short}.md"
    description = " ".join(meta["description"].split())
    yaml_block = "\n".join(
        (
            "inclusion: auto",
            f"name: {meta['name']}",
            f"description: {description}",
        )
    )
    content = f"---\n{yaml_block}\n---\n\n{GENERATED_HEADER.format(src=src)}{body}"
    if not content.endswith("\n"):
        content += "\n"
    out.write_text(content)


def ensure_symlink(link: Path, target_rel: str) -> None:
    if link.is_symlink() or link.exists():
        if link.is_symlink() and os.readlink(link) == target_rel:
            return
        if link.is_dir() and not link.is_symlink():
            shutil.rmtree(link)
        else:
            link.unlink()
    link.parent.mkdir(parents=True, exist_ok=True)
    link.symlink_to(target_rel)


def link_resources(short: str, src: str) -> None:
    src_dir = SKILLS_DIR / src
    bundle_dir = STEERING_DIR / short
    for sub in ("references", "examples"):
        link = bundle_dir / sub
        if (src_dir / sub).is_dir():
            # link sits at steering/<short>/<sub>
            # target sits at skills/<src>/<sub>
            # relative: up 2 (sub -> short -> steering -> REPO)
            target = f"../../skills/{src}/{sub}"
            ensure_symlink(link, target)
        elif link.is_symlink():
            link.unlink()

    if bundle_dir.exists() and not any(bundle_dir.iterdir()):
        bundle_dir.rmdir()


def clean_orphans(active_shorts: set[str]) -> None:
    if not STEERING_DIR.exists():
        return
    for entry in STEERING_DIR.iterdir():
        if entry.is_file() and entry.suffix == ".md":
            if entry.stem not in active_shorts:
                entry.unlink()
        elif entry.is_dir():
            if entry.name not in active_shorts:
                shutil.rmtree(entry)


def main() -> int:
    skills = sorted(p for p in SKILLS_DIR.glob("buildkite-*") if (p / "SKILL.md").exists())
    if not skills:
        print("No skills/buildkite-*/SKILL.md found", file=sys.stderr)
        return 1

    active = set()
    for skill_dir in skills:
        src = skill_dir.name
        short = src.removeprefix("buildkite-")
        active.add(short)
        meta, body = parse_skill(skill_dir / "SKILL.md")
        body = rewrite_links(body, short)
        write_steering_file(short, src, meta, body)
        link_resources(short, src)
        print(f"  steering/{short}.md")

    clean_orphans(active)
    return 0


if __name__ == "__main__":
    sys.exit(main())
