"""Data structures for the memory pipeline.

Defines the core dataclasses used across all pipeline stages: extraction,
summarization, consolidation, and team digest. Each dataclass is a plain
value object with no business logic beyond formatting.

Typical usage::

    from pipeline.types import ExtractResult, TokenUsage

    result = ExtractResult(exchanges="...", position=42, human_count=5)
    usage = TokenUsage(input=1200, output=300, cache=800, cost_usd=0.0021)
    print(usage)  # "1200+800cache→300out ($0.0021)"
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class TokenUsage:
    """Token counts and estimated cost from a single Haiku API call.

    Tracks input, output, and cache-read token counts along with the
    computed USD cost. Used for logging and cost monitoring across all
    pipeline stages.

    Attributes:
        input: Total input tokens sent (includes cached tokens).
        output: Output tokens generated by the model.
        cache: Input tokens served from cache (subset of input).
        cost_usd: Estimated cost in USD, computed from per-token pricing.
    """

    input: int = 0
    output: int = 0
    cache: int = 0
    cost_usd: float = 0.0

    def __str__(self) -> str:
        """Format as a compact summary string for log output."""
        return f"{self.input}+{self.cache}cache→{self.output}out (${self.cost_usd:.4f})"


@dataclass
class HaikuResult:
    """Parsed response from a Haiku CLI invocation.

    Wraps the model's text output along with token usage metadata and
    a flag indicating whether the model chose to skip processing.

    Attributes:
        text: The model's text response (may be empty on error).
        tokens: Token usage and cost for this call.
        is_skip: True if the response starts with "SKIP", indicating
            the model determined there was nothing worth summarizing.
    """

    text: str = ""
    tokens: TokenUsage = field(default_factory=TokenUsage)
    is_skip: bool = False


@dataclass
class ExtractResult:
    """Result of extracting human/assistant exchanges from a session JSONL.

    Produced by ``extract.extract_session()``. Contains the formatted
    exchange text and metadata about what was extracted.

    Attributes:
        exchanges: Formatted text of all extracted exchanges, with role
            headers ([HUMAN] / [AGENT]) and separator lines.
        position: Total line count in the JSONL file (used as the save
            position for incremental extraction).
        human_count: Number of human (user) messages extracted.
        assistant_count: Number of assistant messages extracted.
        corrupt_lines: Number of lines that failed JSON parsing.
    """

    exchanges: str = ""
    position: int = 0
    human_count: int = 0
    assistant_count: int = 0
    corrupt_lines: int = 0


@dataclass
class SaveResult:
    """Result of a save operation that appends a summary to staging.

    Attributes:
        action: Outcome of the save — one of "appended", "skip", or "error".
        entry: The summary text that was appended (empty on skip/error).
        position: JSONL line position at the time of save.
        tokens: Token usage from the Haiku summarization call.
    """

    action: str = ""       # "appended" | "skip" | "error"
    entry: str = ""        # the text appended (or empty)
    position: int = 0      # JSONL line position
    tokens: TokenUsage = field(default_factory=TokenUsage)


@dataclass
class ConsolidationResult:
    """Result of consolidating staging files into recent and archive memory.

    Produced by ``consolidate.consolidate()``. Contains the new file
    contents that the shell script writes to ``recent.md`` and ``archive.md``.

    Attributes:
        recent: New content for recent.md (active, high-relevance entries).
        archive: New content for archive.md (older, compressed entries).
        tokens: Token usage from the Haiku consolidation call.
    """

    recent: str = ""
    archive: str = ""
    tokens: TokenUsage = field(default_factory=TokenUsage)
